CC=clang
CFLAGS=-g -o

all: ex1 ex2 ex3 ex4

clean:
	rm -rf *.o

ex1: ex1.c
	$(CC) $(CFLAGS) ex1 ex1.c

ex2: ex2.c
	$(CC) $(CFLAGS) ex2 ex2.c

ex3: ex3.c
	$(CC) $(CFLAGS) ex3 ex3.c

ex4: ex4.c
	$(CC) $(CFLAGS) ex4 ex4.c
